#use this template to create config.yaml file
APP_PREFIX: "cvs"
ENVIRONMENT_NAME: "test"
ACCOUNT: ""
REGION: "us-east-1"
ECS_NODE_AMI: "ami-0bd2f238e75f8092a"
FLEETWISE_EDGE_IMAGE: "public.ecr.aws/aws-iot-fleetwise-edge/aws-iot-fleetwise-edge:v1.1.1"
SIMULATOR_MEMORY_LIMIT: 512
SIMULATOR_MEMORY_RESERVATION: 256
LOCATION_MAP_STYLE: "VectorEsriTopographic"
ROUTE_MAP_STYLE: "VectorEsriLightGrayCanvas"